name: fonta_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  shared_preferences: ^2.3.5
  pretty_dio_logger: ^1.4.0
  hooks_riverpod: ^2.6.1
  intl: ^0.20.1
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.17
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  go_router: ^14.6.3
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  logger: ^2.5.0
  pull_to_refresh_flutter3: ^2.0.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
